name: ServiceNow Change Request Automation

on:
  pull_request:
    types: [opened, closed]
  push:
    branches:
      - main

jobs:
  create-change-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create ServiceNow Change Request
      env:
        SNOW_INSTANCE_URL: ${{ secrets.SNOW_INSTANCE_URL }}
        SNOW_USER: ${{ secrets.SNOW_USER }}
        SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" == "opened" ]]; then
          export CHANGE_TYPE="New PR"
        elif [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" == "closed" ]]; then
          export CHANGE_TYPE="Merged PR"
        else
          export CHANGE_TYPE="Code Push"
        fi

        export DATA='{
          "short_description": "Automated Change Request from GitHub Actions - Testing",
          "description": "'"$CHANGE_TYPE"' in GitHub repository \n '"$GITHUB_REPOSITORY"' \n '"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/pull/$GITHUB_REF"'"
        }'

        curl -X POST "$SNOW_INSTANCE_URL/api/now/table/change_request" \
        --header "Accept: application/json" \
        --header "Content-Type: application/json" \
        --user "$SNOW_USER:$SNOW_PASSWORD" \
        --data "$DATA" \
        --fail || echo "Failed to create change request"
