name: ServiceNow Change Request Automation

# Trigger the workflow on pull request events and push to the main branch
on:
  pull_request:
    types: [opened, closed]
  push:
    branches:
      - main
    paths-ignore:
      - '**/*'  # Prevent triggering on push if unnecessary

jobs:
  create-change-request:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set CHANGE_TYPE based on event
    - name: Determine Change Type
      id: set_change_type
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" == "opened" ]]; then
          echo "CHANGE_TYPE=New PR" >> $GITHUB_ENV
        elif [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" == "closed" ]]; then
          echo "CHANGE_TYPE=Merged PR" >> $GITHUB_ENV
        else
          echo "CHANGE_TYPE=Code Push" >> $GITHUB_ENV
        fi
      shell: bash

    # Step 3: Create ServiceNow Change Request only for specific events
    - name: Create ServiceNow Change Request
      if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
      env:
        CHANGE_TYPE: ${{ env.CHANGE_TYPE }}
        SNOW_INSTANCE_URL: ${{ secrets.SNOW_INSTANCE_URL }}
        SNOW_USER: ${{ secrets.SNOW_USER }}
        SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
      run: |
        # Construct the change request data payload
        export DATA='{
          "short_description": "Automated Change Request from GitHub Actions",
          "description": "'"$CHANGE_TYPE"' in GitHub repository \n '"$GITHUB_REPOSITORY"' \n '"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/pull/$GITHUB_REF"'",
        }'

        # Send a POST request to ServiceNow to create the change request
        curl -X POST "$SNOW_INSTANCE_URL/api/now/table/change_request" \
        --header "Accept: application/json" \
        --header "Content-Type: application/json" \
        --user "$SNOW_USER:$SNOW_PASSWORD" \
        --data "$DATA" \
        --fail || echo "Failed to create change request in ServiceNow"
