name: Create ServiceNow Change Request

# Trigger this workflow when a PR is created or merged
on:
  pull_request:
    types: [opened, closed]
  push:
    branches:
      - main

jobs:
  create-change-request:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Call the ServiceNow API to create/update the change request
    - name: Create ServiceNow Change Request
      run: |
        curl -X POST https://your-instance.service-now.com/api/now/table/change_request \
        --header "Accept: application/json" \
        --header "Content-Type: application/json" \
        --user "${{ secrets.SNOW_USER }}:${{ secrets.SNOW_PASSWORD }}" \
        --data '{
          "short_description": "Code change triggered by GitHub PR",
          "description": "PR merged in repository",
          "u_git_repo": "'$GITHUB_REPOSITORY'",
          "u_pr_link": "'$GITHUB_EVENT_PATH'",
          "u_change_reason": "Automated change from GitHub Actions"
        }'

    # Step 3: Output a success message (optional)
    - name: Success
      run: echo "Change request created in ServiceNow"
