name: Update ServiceNow Change Request

on:
  pull_request:
    types: [closed]  # Trigger when a pull request is closed (merged)

jobs:
  update-change-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update ServiceNow Change Request
      env:
        SNOW_INSTANCE_URL: ${{ secrets.SNOW_INSTANCE_URL }}
        SNOW_USER: ${{ secrets.SNOW_USER }}
        SNOW_PASSWORD: ${{ secrets.SNOW_PASSWORD }}
      run: |
        # Define the sys_id of the change request to update
        CHANGE_REQUEST_SYS_ID="f3d65be5c3f51a104fcd50311501311e"

        # Define the data payload for the update
        DATA='{
          "business_service": "Network",
          "service_offering": "Network Management Applications",
          "comments": "'"$GITHUB_REF"' \n '"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/pull/$GITHUB_REF"'"
        }'

        # Send the PUT/PATCH request to ServiceNow API to update the change request
        curl -X PUT "$SNOW_INSTANCE_URL/api/sn_chg_rest/change/$CHANGE_REQUEST_SYS_ID" \
        --header "Accept: application/json" \
        --header "Content-Type: application/json" \
        --user "$SNOW_USER:$SNOW_PASSWORD" \
        --data "$DATA" \
        --fail || echo "Failed to update the change request in ServiceNow"
